services:
  - type: web
    name: veloce-website
    env: node
    plan: free # Can be upgraded for more performance
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: NODE_ENV=production npx tsx server/src/index.ts
    envVars:
      - key: PORT
        value: 3000
