services:
  - type: web
    name: veloce-website
    env: node
    plan: free # Can be upgraded for more performance
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
